[Settings]

# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
	status = 200

[[headers]]
	for = "/*"
	[headers.values]
		Content-Security-Policy = "frame-ancestors 'none'"
		X-Content-Type-Options = "nosniff"
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"